### ISSUE TITLE
WARDuino dump unit test fails sometimes

### ISSUE THREAD

**Issue by tolauwae** [TOPLLab/WARDuino-VSCode#15]
Eventhough all the correct dump information has been received the test times out:

```
got a message ... 
12 
Interrupt: 12
{
"pc":"0x56430c22296d","start":["0x56430c222900"],"breakpoints":[],
"functions":[{"fidx":"0x0","from":"0x56430c222968","to":"0x56430c222968"},{"fidx":"0x1","from":"0x56430c22296b","to":"0x56430c2229a2"},{"fidx":"0x2","from":"0x56430c2229a7","to":"0x56430c2229b8"}],"callstack":[{"type":0,"fidx":"0x2","sp":-1,"fp":-1,"start":"0x56430c2229a7","ra":"0x56430c22295f","callsite":"0x56430c22295d"},{"type":3,"fidx":"0x0","sp":0,"fp":0,"start":"0x56430c2229ab","ra":"0x56430c2229ad","callsite":"0x56430c2229ab"},{"type":0,"fidx":"0x1","sp":0,"fp":0,"start":"0x56430c22296b","ra":"0x56430c2229b3","callsite":"0x56430c2229b1"},{"type":4,"fidx":"0x0","sp":3,"fp":1,"start":"0x56430c222970","ra":"0x56430c222972","callsite":"0x56430c222970"},{"type":0,"fidx":"0x1","sp":2,"fp":1,"start":"0x56430c22296b","ra":"0x56430c22297e","callsite":"0x56430c22297c"},{"type":4,"fidx":"0x0","sp":5,"fp":3,"start":"0x56430c222970","ra":"0x56430c222972","callsite":"0x56430c222970"},{"type":0,"fidx":"0x1","sp":4,"fp":3,"start":"0x56430c22296b","ra":"0x56430c22297e","callsite":"0x56430c22297c"}], "locals": {"count":0,"locals":[]}}



Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/tolauwae/Documents/TOPL/plugin/src/test/UnitTests/TestDebuggerBridge.ts)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by tolauwae** [comment]
This test has been superceded by the Latch test suite. Closing issue.
